# vi: set ft=ruby :

BASE_IP = "192.168.33"

VM_TYPES = ["master", "agent", "puppetdb", "console", "compile", "postgresql"]
BOXES = [
    #{:box => "puppetlabs/ubuntu-14.04-64-nocm", :name => "ubuntu14"},
    #{:box => "puppetlabs/ubuntu-12.04-64-nocm", :name => "ubuntu12"},
    #{:box => "puppetlabs/centos-6.6-64-nocm", :name => "centos6"},
    {:box => "puppetlabs/centos-7.0-64-nocm", :name => "centos7"},
    #{:box => "puppetlabs/debian-7.8-64-nocm", :name => "debian7"},
    #{:box => "puppetlabs/debian-6.0.10-64-nocm", :name => "debian6"},
]

# Helper Functions

def create_vm(config, box, name)
    cpus = 1
    memory = 512
    ip = 9
    boxname = box[:name]
    box = box[:box]
    hostname = name.to_s
    scripts = []

    case name.to_s
    when /master.*/
        memory = 2048
        hostname = "master.vm"
    when /agent.*/
        hostname = "agent.vm"
    when /puppetdb.*/
        hostname = "puppetdb.vm"
    when /console.*/
        hostname = "console.vm"
    when /compile.*/
        memory = 2048
        hostname = "compile.vm"
    when /postgresql.*/
        hostname = "postgresql.vm"
    end

    ip = get_vm_ip name

    ip_modifier = /\S+(\d+).*/.match(name)
    if ip_modifier
        ip_modifier = ip_modifier[1].to_i
    else
        ip_modifier = 1
    end
    ip = 10 * ip_modifier + ip
    ip = "#{BASE_IP}.#{ip}"
    name = "#{name}-#{boxname}.vm"

    scripts.push get_ip_addresses(ip_modifier)
    scripts.push get_platform_scripts(boxname)

    config.vm.define name.to_sym do |vbox|
        vbox.vm.box = box
        vbox.vm.hostname = hostname
        vbox.vm.network "private_network", ip: ip
        vbox.vm.provider "virtualbox" do |v|
            v.cpus = cpus
            v.name = name
            v.memory = memory
        end
        scripts.each do |script|
            vbox.vm.provision "shell", inline: script
        end
    end
end

def get_vm_ip(hostname)
    case hostname.to_s
    when /master.*/
        0
    when /agent.*/
        1
    when /puppetdb.*/
        2
    when /console.*/
        3
    when /compile.*/
        4
    when /postgresql.*/
        5
    end
end

def get_ip_addresses(modifier)
    VM_TYPES.map do |vm|
        ip = get_vm_ip(vm) + (10 * modifier)
        if modifier == 1
          modifier_str = ""
        else
          modifier_str == modifier
        end
        "echo '192.168.33.#{ip} #{vm}#{modifier_str}.vm' >> /etc/hosts"
    end.join("\n")
end


def get_platform_scripts(boxname)
    el_script = <<-SCRIPT
    sudo service firewalld stop
    SCRIPT

    deb_script = <<-SCRIPT
    sudo apt-get update
    sudo apt-get install -y build-essential git python vim tmux zsh ruby1.9.1-dev

    sudo -H -u vagrant bash -c 'git clone https://github.com/demophoon/dotfiles ~/dotfiles'
    sudo -H -u vagrant bash -c 'git clone https://github.com/demophoon/vundle-headless-installer.git ~/vundle-headless-installer'
    sudo -H -u vagrant bash -c 'git --git-dir=~/dotfiles submodule update --init'
    sudo -H -u vagrant bash -c 'source ~/dotfiles/setup.sh -f'
    sudo -H -u vagrant bash -c 'python ~/vundle-headless-installer/install.py'
    SCRIPT

    case boxname
    when /ubuntu.*/
        deb_script
    when /centos.*|el.*/
        el_script
    else
        nil
    end
end

def create_pe_vms(config, box, suffix)
    VM_TYPES.each { |type| create_vm(config, box, "#{type}#{suffix}") }
end

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.synced_folder "/Users/britt/projects", "/local", type: "nfs"
    config.vm.synced_folder "/Users/britt/projects/vagrant/ubuntu-master", "/vagrant", type: "nfs"
    BOXES.map { |box|
        create_pe_vms config, box, ""
        create_pe_vms config, box, "2"
    }

    config.vm.provision "shell", inline: <<-SCRIPT
    mkdir -p /root/.ssh/
    cat /local/work/yellow/pe_acceptance_tests/id_rsa-acceptance.pub > /root/.ssh/authorized_keys
    SCRIPT
end
