#!/bin/bash

if [ ! -z $1 ]; then
    PROJ_NAME=${1}
else
    PROJ_NAME="untitled_project"
fi

unset TMUX

if tmux has-session -t "$PROJ_NAME"; then
    echo "Attaching to session $PROJ_NAME"
else
    echo "Creating session $PROJ_NAME"
    tmux new-session -d -s "$PROJ_NAME"
fi

ATTACH_COMMAND="tmux attach-session ${*:2} -t $PROJ_NAME"
$ATTACH_COMMAND
