#!/bin/bash

PROJECT_NAME=${PROJECT_NAME:-${1}}
PROJECT_NAME=${PROJECT_NAME:-$(basename $(pwd))}
tmux='tmux'
shift

if [ -n "${TMUX_SOCKET}" ]; then
    tmux="${tmux:?} -S ${TMUX_SOCKET}"
fi

session_exists() {
    ${tmux:?} has-session -t "${PROJECT_NAME}" 2>/dev/null
    return $?
}

create_session() {
    ${tmux:?} new-session -d -s "${PROJECT_NAME}"
}

attach_session() {
    ${tmux:?} attach-session "$@" -t "${PROJECT_NAME}"
}

default_customize_session() {
    colors=(
        27
        34
        39
        124
        136
        141
        208
    )
    #colors=({1..127})

    num_colors=${#colors[@]}

    # Set color to determined random color
    color_num=$(bash -c "RANDOM=$(hostname | tr '.[a-zA-Z]' '0-9'); echo \$RANDOM")
    color_num=$((${color_num}%${num_colors}))
    _TMUX_COLOR=${colors[${color_num}]}

    # Set color to determined random color
    ${tmux:?} set-option status-fg "colour253" > /dev/null
    ${tmux:?} set-option status-bg "colour${_TMUX_COLOR}" > /dev/null
}

if ! session_exists; then
    if [ -n "${TMUX_SOCKET}" ]; then
        rm -f "${TMUX_SOCKET}"
    fi
    create_session

    if type 'customize_session' 2>/dev/null | grep -q 'function'; then
        customize_session "${tmux:?}"
    else
        default_customize_session
    fi
fi

attach_session "$@"
