#!/bin/sh
# Give dmenu list of all unicode characters to copy.
# Shows the selected character in dunst if running.

# Must have xclip installed to even show menu.
xclip -h >/dev/null || exit

emoji=$(grep -v '#' ~/.emoji | cut -f 2 | dmenu -i -l 20 -p "Emoji?" -fn Monospace-20)

[ "$emoji" != "" ] || exit

selected=$(grep -v '#' ~/.emoji | grep -P "\t${emoji}\t" | cut -f 1 | cut -d' ' -f 1)
echo "$selected" | tr -d '\n' | xclip -selection clipboard
notify-send "'$selected' copied to clipboard." &
