#!/bin/sh
# Give dmenu list of all unicode characters to copy.
# Shows the selected character in dunst if running.

# Must have xclip installed to even show menu.
xclip -h >/dev/null || exit

emoji=$(cat ~/.emoji | sed 's/;.*//' | cut -d' ' -f 2- | dmenu -l 20 -p "Emoji?")

[ "$emoji" != "" ] || exit

c=$(cat ~/.emoji | sed 's/;.*//' | grep "${emoji}" | cut -d' ' -f 1)
echo "$c" | tr -d '\n' | xclip -selection clipboard
notify-send "'$c' copied to clipboard." &
