#!/bin/bash
# Follow guide at link below to setup wwan
# https://docs.ubuntu.com/core/en/stacks/network/network-manager/docs/configure-cellular-connections

case ${1} in
    enable|on)
        nmcli r wwan on
        echo "Cellular data enabled"
        ;;
    disable|off)
        nmcli r wwan off
        echo "Cellular data disabled"
        ;;
esac
