#!/bin/bash

# Magic security words
words=$(shuf -n3 /usr/share/dict/american-english | tr '\n' ' ')

scrot /tmp/screen.png
convert /tmp/screen.png \
    -filter spline -scale 10% \
    -fill black -colorize 75% \
    -gravity center \
    -pointsize 72 \
    -filter box -scale 1000% \
    -fill white -annotate 0 "${words}" \
    /tmp/screen.png

i3lock -i /tmp/screen.png -u -n
