#!/bin/bash
#
# The `pairing` command is used to start a shared tmux session on a machine
# automatically.
# This script should take care of session management as well as
# opening up the session to the world.
#
# WARNING: THIS WILL LEAVE YOUR ACCOUNT ACCESSIBLE TO ANYONE WHO HAS ACCESS TO
# LOGIN TO THE MACHINE. KILL YOUR TMUX SESSION TO END SHARING. DO NOT JUST
# DETACH FROM THE TMUX SESSION.
#
# For automatic pairing when logging in via ssh configure the authorized_keys
# file.
# Putting "command='tmux -S /tmp/pairing' attach-session -t pairing" before the
# ssh key will automatically connect that ssh key to the 'pairing' server.

PROJECT_NAME='pairing'
TMUX_SOCKET='/tmp/pairing-tmux.sock'

customize_session() {
    tmux=$1

    ${tmux:?} send-keys -t "$PROJECT_NAME unset TMUX; reset" c-m
    ${tmux:?} set-option status off
    ${tmux:?} set-option status-position top
    ${tmux:?} set-option prefix c-a

    chmod 777 "${TMUX_SOCKET:?}"
}

# shellcheck disable=SC1090
source "$(which attach)"
