#!/bin/bash

PROJECT_NAME='sandbox'

customize_session() {
    tmux=$1

    ${tmux:?} send-keys -t "$PROJECT_NAME unset TMUX; reset" c-m
    ${tmux:?} set-option -t "$PROJECT_NAME" prefix c-a
    ${tmux:?} set-option -t "$PROJECT_NAME" status off
    ${tmux:?} set-option status-position top
}

# shellcheck disable=SC1090
source "$(which attach)"
