#!/bin/bash

PROJ_NAME="sandbox"

if tmux has-session -t "$PROJ_NAME"; then
    echo "Attaching to session $PROJ_NAME"
else
    echo "Creating session $PROJ_NAME"
    tmux new-session -d -s "$PROJ_NAME"

    tmux send-keys -t $PROJ_NAME "unset TMUX; reset" c-m

    tmux set-option -t $PROJ_NAME prefix c-a

    #tmux unbind-key -t $PROJ_NAME c-b
    tmux bind-key c-a send-prefix

    tmux set-option -t $PROJ_NAME status off
    tmux set-option status-position top
fi

if [ ! -z $1 ]; then
    tmux attach-session -dt "$PROJ_NAME"
else
    tmux attach-session -t "$PROJ_NAME"
fi
