#!/usr/bin/env python
# encoding: utf-8

import sys
import os

from subprocess import call


def cmd(command, suppress_warning=False):
    return_code = call(command)
    if return_code != 0 and not suppress_warning:
        print("Couldn't perform `{}`".format(' '.join(command)))
        exit(return_code)


def main():
    old_environ = os.environ.get("VAGRANT_DOTFILE_PATH", "")
    if not os.path.isfile('Vagrantfile'):
        os.environ["VAGRANT_CWD"] = os.path.join(os.path.dirname(
            os.path.realpath(os.path.expanduser("~/.bashrc"))
        ), "files/vagrant")
    args = sys.argv[1:]
    if not args:
        cmd(["vagrant"] + args, suppress_warning=True)
    elif args[0] == 'boot':
        cmd(["vagrant", "up"] + args[1:])
        cmd(["vagrant", "ssh"] + args[1:])
    elif args[0] == 'reboot':
        cmd(["vagrant", "destroy", "--force"] + args[1:])
        cmd(["vagrant", "up"] + args[1:])
        cmd(["vagrant", "ssh"] + args[1:])
    else:
        cmd(["vagrant"] + args, suppress_warning=True)

    os.environ["VAGRANT_CWD"] = old_environ

if __name__ == '__main__':
    main()
