#!/bin/bash

bat_id=$1

PLAYING_ICON=${icon:-$(xrescat i3xrocks.label.mediaplaying "")}

battery0="$( upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep percentage | grep -E -o '[0-9][0-9]+')"
battery1="$( upower -i /org/freedesktop/UPower/devices/battery_BAT1 | grep percentage | grep -E -o '[0-9][0-9]+')"

if [ -z "${bat_id}" ]; then
    battery=${battery0}
    battery_count=1
    if [ ! -z $battery1 ]; then
        battery=$(expr $battery + $battery1)
        battery_count=2
    fi
    battery=$(expr $battery / $battery_count)
else
    bat_name="battery${bat_id}"
    battery="${!bat_name}"
    battery_status=$(upower -i /org/freedesktop/UPower/devices/battery_BAT${bat_id} | grep state | cut -d':' -f2 | tr -d '[:space:]')
fi

full_text="$battery"
short_text="$battery"
color='#333333'
urgent=0

case $battery in
    9?|10?)
        color='#0f0'
        icon=i3xrocks.label.battery100
        ;;
    6?|7?|8?)
        color='#ff0'
        icon=i3xrocks.label.battery80
        ;;
    3?|4?|5?)
        color='#f60'
        icon=i3xrocks.label.battery50
        ;;
    2?)
        color='#fff'
        icon=i3xrocks.label.battery20
        urgent=33
        ;;
    *)
        color='#fff'
        icon=i3xrocks.label.battery0
        urgent=33
        ;;
esac

icon_color=$color
case $battery_status in
    charging)
        icon=i3xrocks.label.batterycharging
        icon_color="#0f0"
        ;;
    fully-charged)
        icon=i3xrocks.label.batteryac
        ;;
esac

icon=$(xrescat ${icon})

bat="BAT"
if [ "${bat_id}" = "0" ]; then
   bat="INT"
elif [ "${bat_id}" = "1" ]; then
   bat="EXT"
fi

if [ ! -z "${battery}" ]; then
    full_text="<span color=\"${icon_color}\">${icon}</span><span color=\"${color}\">: ${full_text}</span>"
else
    full_text=''
fi

echo "${full_text}"
echo "${full_text}"
exit $urgent
