#!/bin/sh

source ~/.config/regolith/i3xrocks/commands/_helpers.sh

ssid=$(iwgetid -r)

full_text="$ssid"
short_text="$ssid"
color='#ff0000'

if [ -z "$ssid" ]; then
    full_text="Not Connected"
else

    case "$(curl -s --max-time 2 -I https://www.brittg.com | sed 's/^[^ ]*  *\([0-9]\).*/\1/; 1q')" in
      [23])
          color='#00ff00'
          ;;
      5)
          full_text="$ssid - 500"
          color='#ffff00'
          ;;
      *)
          if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then
              if ping -q -c 1 -W 1 google.com >/dev/null; then
                  color='#ffff00'
              else
                  full_text="$ssid - Network Failure"
                  color='#ff6600'
              fi
          else
              full_text="$ssid - IPv4 Down"
          fi
          ;;
    esac

fi

echo "${full_text}"
echo "${full_text}"
echo "${color}"
