#!/bin/sh

volume="$(amixer -D pulse get Master | grep 'Left' | awk -F'[][]' '{ print $2 }' | grep -E -o '[0-9][0-9]+')"

full_text="$volume"
short_text="$volume"
color='#333333'

case $volume in
    9?|10?)
        color='#ffffff'
    ;;
    7?|8?)
        color='#cccccc'
    ;;
    5?|6?)
        color='#aaaaaa'
    ;;
    3?|4?)
        color='#888888'
    ;;
    ?)
        color='#666666'
    ;;
esac

echo "VOL: ${full_text}"
echo "${short_text}"
echo "${color}"
